@todoId1 = 111
@todoId2 = 222
@todoId3 = 333
### POST a new To-Do
POST http://localhost:5001/api/todo HTTP/1.1
Content-Type: application/json

{
        "id": "{{todoId1}}",
        "details": "Hello from {{todoId1}}"
}

### POST a new To-Do
POST http://localhost:5001/api/todo HTTP/1.1
Content-Type: application/json

{
        "id": "{{todoId2}}",
        "details": "Hello from {{todoId2}}"
}

### POST a new To-Do
POST http://localhost:5001/api/todo HTTP/1.1
Content-Type: application/json

{
        "id": "{{todoId3}}",
        "details": "Hello from {{todoId3}}"
}

### GET particular To-Do

GET http://localhost:5001/api/Todo/{{todoId}} HTTP/1.1
Content-Type: application/json